version: '3.1'
services:
  web:
    stdin_open: true
    tty: true
    command: --dev=all
  db:
      ports:
      - "5433:5432"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1029:1025
      - 8029:8025
      